various fixes
reverts interpreter to /bin/sh
reindents according to .editorconfig
exits showing usage when no arguments are received
improves creation of new session files

diff --git a/tmuxstart b/tmuxstart
--- a/tmuxstart
+++ b/tmuxstart
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/sh
 
 sessiondir=${TMUXSTART_DIR:-$HOME/.tmuxstart}
 
@@ -11,50 +11,57 @@ new_window\n
 
 # Print usage information if there's not exactly 1 argument
 usage() {
-  # TODO: print all available options
-  echo "Usage: $(basename $0) tmux-session"
-  exit 1
+    # TODO: print all available options
+    echo "Usage: $(basename $0) tmux-session"
+    exit 1
 }
 
 while getopts ':hlo:d:' option; do
-  case "${option}" in
-    h)
-      usage ;;
-    l)
-      ls -1 $sessiondir; exit 0 ;;
-    o)
-      sessionfile="${sessiondir}/${OPTARG}"
-      if [ ! -f $sessionfile ]; then
-        #TODO: check if vim, else create file
-        echo -e $sessionexample | $EDITOR - +"file ${sessionfile}"
-        # echo -e $sessionexample > $sessionfile;
-      else
-        ${EDITOR:-vi} $sessionfile
-      fi
-      exit 0
-      ;;
-    d)
-      sessionfile="${sessiondir}/${OPTARG}"
-      if [[ -f $sessionfile ]]; then
-        echo "Are you sure you want to remove ${OPTARG}? [y/N]"
-        read confirm
-        [[ $confirm =~ 'y' ]] && rm -v $sessionfile
-      fi
-      exit
-      ;;
-    *)
-      echo "Invalid option"
-      usage
-      ;;
-  esac
+    case "${option}" in
+        h)
+            usage ;;
+        l)
+            ls -1 $sessiondir; exit 0 ;;
+        o)
+            sessionfile="${sessiondir}/${OPTARG}"
+            if [ ! -f $sessionfile ]; then
+                # EDITOR not explicitly set or uses vim
+                # create a buffer with dummy content in $TMUXSTART_DIR
+                if [ -z "$EDITOR" -o "$EDITOR" = 'vi' -o "$EDITOR" = 'vim' ]; then
+                    echo "${sessionexample}" | ${EDITOR:-vi} - +"file ${sessionfile}"
+                else
+                    echo "${sessionexample}" > $sessionfile;
+                    $EDITOR $sessionfile
+                fi
+            else
+                ${EDITOR:-vi} $sessionfile
+            fi
+            exit 0
+            ;;
+        d)
+            sessionfile="${sessiondir}/${OPTARG}"
+            if [ -f $sessionfile ]; then
+                echo "Are you sure you want to remove \"${OPTARG}\"? [y/N]"
+                read confirm
+                [ $confirm = 'y' ] && rm -v $sessionfile
+            else
+                echo "Session file for \"${OPTARG}\" not found."
+            fi
+            exit
+            ;;
+        *)
+            echo "Invalid option"
+            usage
+            ;;
+    esac
 done
 
 # Some helper functions for simpler session files
 new_session() {
-  # Set default path based on $path variable if defined
-  [ "$path" ] && cd "$path"
-  tmux new-session -d -s $session "$@"
-  [ "$path" ] && set_path "$path"
+    # Set default path based on $path variable if defined
+    [ "$path" ] && cd "$path"
+    tmux new-session -d -s $session "$@"
+    [ "$path" ] && set_path "$path"
 }
 new_window() { tmux new-window -d -t $session "$@"; }
 kill_window() { tmux kill-window -t $session:"$@"; }
@@ -67,20 +74,23 @@ set_path() { tmux set-option -t $session default-path "$@"; }
 split() { tmux split-window -t $session:"$@"; }
 swap() { tmux swap-pane -t $session:"$@"; }
 
+# no arguments received
+[ $# -eq 0 ] && usage
+
 # normal session management
 session=$1
 TMUX_OLD=$TMUX
 TMUX=
 if ! tmux has-session -t $session ; then
-  if [ -f "$sessiondir/$1" ] ; then
-    . "$sessiondir/$1"
-  else
-    tmux new-session -d -s $session
-  fi
+    if [ -f "$sessiondir/$1" ] ; then
+        . "$sessiondir/$1"
+    else
+        tmux new-session -d -s $session
+    fi
 fi
 if [ "$TMUX_OLD" = "" ]; then
-  tmux attach-session -t $session
+    tmux attach-session -t $session
 else
-  tmux switch-client -t $session
+    tmux switch-client -t $session
 fi
 TMUX=$TMUX_OLD
